/*
 * VT100.h
 *
 *  Created on: Feb 13, 2017
 *      Author: clausr
 */

#ifndef VT100_H_
#define VT100_H_

#define VT100_RESET()               "\ec"
#define VT100_CURSOR_HOME( row, col )       "\e[" #row ";" #col "H"
#define VT100_CURSOR_UP( count )        "\e[" #count "A"
#define VT100_CURSOR_DOWN( count )        "\e[" #count "B"
#define VT100_CURSOR_FORWARD( count )       "\e[" #count "C"
#define VT100_CURSOR_BACKWARD( count )      "\e[" #count "D"
#define VT100_CURSOR_POSITION( row, col )     "\e[" #row ";" #col "f"
#define VT100_SAVE_CURSOR()           "\e[s"
#define VT100_UNSAVE_CURSOR()           "\e[u"
#define VT100_SAVE_CURSOR_ATTR()        "\e7"
#define VT100_RESTORE_CURSOR_ATTR()        "\e8"
#define VT100_SCROLL_SCREEN()           "\e[r"
#define VT100_SCROLL( startRow, endRow )    "\e[" #startRow ";" #endRow "r"
#define VT100_SCROLL_DOWN()           "\eD"
#define VT100_SCROLL_UP()             "\eM"
#define VT100_SET_TAB()             "\eH"
#define VT100_CLEAR_TAB()             "\e[g"
#define VT100_CLEAR_TABS()            "\e[3g"
#define VT100_ERASE_END()             "\e[K"
#define VT100_ERASE_START()           "\e[1K"
#define VT100_ERASE_LINE()            "\r\e[2K\r"
#define VT100_ERASE_DOWN()            "\e[J"
#define VT100_ERASE_IP()            "\e[1J"
#define VT100_ERASE_SCREEN()          "\e[2J"
#define VT100_ENABLE_LINE_WRAP()          "\e[7h"
#define VT100_DISABLE_LINE_WRAP()          "\e[7l"
#define VT100_ATTR_AND              ";"
#define VT100_ATTR_RESET            "0"
#define VT100_ATTR_BRIGHT             "1"
#define VT100_ATTR_DIM              "2"
#define VT100_ATTR_ITALIC             "3"
#define VT100_ATTR_UNDERSCORE           "4"
#define VT100_ATTR_BLINK_SLOW           "5"
#define VT100_ATTR_BLINK_RAPID          "6"
#define VT100_ATTR_REVERSE            "7"
#define VT100_ATTR_HIDDEN             "8"
#define VT100_ATTR_CROSS_OUT          "9"
#define VT100_ATTR_DEAFULT_FONT         "10"
#define VT100_ATTR_FONT1            "11"
#define VT100_ATTR_FONT2            "12"
#define VT100_ATTR_FONT3            "13"
#define VT100_ATTR_FONT4            "14"
#define VT100_ATTR_FONT5            "15"
#define VT100_ATTR_FONT6            "16"
#define VT100_ATTR_FONT7            "17"
#define VT100_ATTR_FONT8            "18"
#define VT100_ATTR_FONT9            "19"
#define VT100_ATTR_NORMAL             "22"
#define VT100_ATTR_NO_UNDERLINE         "24"
#define VT100_ATTR_NO_BLINK           "25"
#define VT100_ATTR_NO_REVERSE           "27"
#define VT100_ATTR_NO_HIDDEN          "28"
#define VT100_ATTR_NO_CROSS_OUT         "29"
#define VT100_ATTR_FORE_BLACK           "30"
#define VT100_ATTR_FORE_RED           "31"
#define VT100_ATTR_FORE_GREEN           "32"
#define VT100_ATTR_FORE_YELLOW          "33"
#define VT100_ATTR_FORE_BLUE          "34"
#define VT100_ATTR_FORE_MAGENTA         "35"
#define VT100_ATTR_FORE_CYAN          "36"
#define VT100_ATTR_FORE_WHITE           "37"
#define VT100_ATTR_FORE_DEFAULT         "39"
#define VT100_ATTR_BACK_BLACK           "40"
#define VT100_ATTR_BACK_RED           "41"
#define VT100_ATTR_BACK_GREEN           "42"
#define VT100_ATTR_BACK_YELLOW          "43"
#define VT100_ATTR_BACK_BLUE          "44"
#define VT100_ATTR_BACK_MAGNETA         "45"
#define VT100_ATTR_BACK_CYAN          "46"
#define VT100_ATTR_BACK_WHITE           "47"
#define VT100_ATTR_BACK_DEFAULT         "49"
#define VT100_ATTR( ... )             "\e[" __VA_ARGS__ "m"

#define VT100_WARN( message ) VT100_ATTR(VT100_ATTR_RESET) "[ " VT100_ATTR(VT100_ATTR_FORE_YELLOW) "WARNING" VT100_ATTR(VT100_ATTR_RESET) " ] " message
#define VT100_ERROR( message ) VT100_ATTR(VT100_ATTR_RESET) "[ " VT100_ATTR(VT100_ATTR_FORE_RED) "ERROR" VT100_ATTR(VT100_ATTR_RESET) " ] " message

#endif /* VT100_H_ */
